# Site settings
title: Engine Theme Manual
email: info@enginecomerce.com
description: A complete guide to building themes on the Engine ecommerce platform
baseurl: "/" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
repo_url: "https://github.com/enginecommerce/engine-theme-manual"
repo_issues_url: "https://github.com/enginecommerce/engine-theme-manual/issues"
twitter_username: enginecommerce
github_username:  enginecommerce
timezone: America/Chicago

# Build settings
encoding: utf-8
markdown: kramdown
plugins:
  - jekyll-feed
sass:
  style: compressed

# Content settings
search_enabled: true
theme: just-the-docs
aux_links:
  "Ecommerce Platform":
    - "https://enginecommerce.com"
  "Ecommerce Email":
    - "https://enginemail.io"
permalink: pretty

# Plugins, etc.
google_tag_manager_id: GTM-NQZFWJC

# Security
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - config.ru
